inherit: true

#Copied from https://www.adayinthelifeof.nl/2013/11/20/external-code-coverage-with-travis-scrutinizer/
tools:
    external_code_coverage:
      timeout: 600
      runs: 2
    php_code_sniffer:
      config:
        standard: PSR2
    php_cs_fixer:
      extensions:
        # Default:
        - php
      fixers: []
      enabled: false
      filter:
            paths: [tests/*,src/*]
            excluded_paths: []
coding_style:
  php:
    indentation:
      general:
        use_tabs: false

checks:
    php:
        code_rating: true
        duplication: true

build:
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]
    js:
      root_path: './client/src/js'
      environment:
        node: 6.11.1
      tests:
        override:
          - eslint-run webpack.config.dev.js webpack.config.prod.js client/src/js

filter:
    paths: [tests/*,src/*]
